# Generated by Django 3.1.5 on 2021-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(null=True)),
                ('column', models.CharField(max_length=500)),
                ('value', models.TextField()),
                ('list_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listname', models.CharField(max_length=500)),
                ('Listdescription', models.TextField()),
                ('columns', models.TextField()),
            ],
        ),
    ]
